# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Andi Chandler <andi@gowling.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-18 06:06+0000\n"
"PO-Revision-Date: 2014-12-10 14:35+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: English (United Kingdom) (http://www.transifex.com/projects/p/"
"glance/language/en_GB/)\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: glance/scrubber.py:218
#, python-format
msgid "Failed to find image to delete: %s"
msgstr "Failed to find image to delete: %s"

#: glance/scrubber.py:258
#, python-format
msgid "%s directory does not exist."
msgstr "%s directory does not exist."

#: glance/scrubber.py:583
#, python-format
msgid "Unable to delete URI from image %s."
msgstr ""

#: glance/api/common.py:167
#, python-format
msgid ""
"User %(user)s attempted to upload an image of unknown size that will exceed "
"the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/common.py:176
#, python-format
msgid ""
"User %(user)s attempted to upload an image of size %(size)d that will exceed "
"the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/middleware/version_negotiation.py:67
msgid "Unknown version. Returning version choices."
msgstr "Unknown version. Returning version choices."

#: glance/api/v1/images.py:700
#, python-format
msgid ""
"Failed to activate image %s in registry. About to delete image bits from "
"store and update status to 'killed'."
msgstr ""

#: glance/api/v2/images.py:860
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""
"Could not find schema properties file %s. Continuing without custom "
"properties"

#: glance/api/v2/tasks.py:72
#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr "Forbidden to create task. Reason: %(reason)s"

#: glance/api/v2/tasks.py:110
#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr "Failed to find task %(task_id)s. Reason: %(reason)s"

#: glance/api/v2/tasks.py:115
#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr "Forbidden to get task %(task_id)s. Reason: %(reason)s"

#: glance/cmd/replicator.py:562
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, destination "
"is %(slave_value)s)"
msgstr ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, destination "
"is %(slave_value)s)"

#: glance/cmd/replicator.py:575
#, python-format
msgid "Image %s entirely missing from the destination"
msgstr "Image %s entirely missing from the destination"

#: glance/common/store_utils.py:63
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr "Failed to delete image %s in store from URI"

#: glance/common/scripts/image_import/main.py:158
#, python-format
msgid "Task %(task_id)s failed with exception %(error)s"
msgstr ""

#: glance/db/simple/api.py:355
#, python-format
msgid "Could not find image %s"
msgstr "Could not find image %s"

#: glance/db/simple/api.py:359
msgid "Unable to get deleted image"
msgstr "Unable to get deleted image"

#: glance/db/simple/api.py:363
msgid "Unable to get unowned image"
msgstr "Unable to get unowned image"

#: glance/db/simple/api.py:870
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:875
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:1037
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:73
msgid "Deadlock detected. Retrying..."
msgstr "Deadlock detected. Retrying..."

#: glance/db/sqlalchemy/api.py:113
msgid "Attempted to modify image user did not own."
msgstr "Attempted to modify image user did not own."

#: glance/db/sqlalchemy/api.py:323
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id not in sort_keys; is sort_keys unique?"

#: glance/db/sqlalchemy/metadata.py:240
#, python-format
msgid "Duplicate entry for values: %s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:92
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr "Failed to decrypt location value for image %(image_id)s"

#: glance/image_cache/__init__.py:72
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."

#: glance/image_cache/__init__.py:93
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"

#: glance/image_cache/prefetcher.py:47
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr "Image '%s' is not active. Not caching."

#: glance/image_cache/prefetcher.py:52
#, python-format
msgid "No metadata found for image '%s'"
msgstr "No metadata found for image '%s'"

#: glance/image_cache/prefetcher.py:80
msgid "Failed to successfully cache all images in queue."
msgstr "Failed to successfully cache all images in queue."

#: glance/image_cache/drivers/sqlite.py:333
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"

#: glance/image_cache/drivers/sqlite.py:459
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr "Failed to delete file %(path)s. Got error: %(e)s"

#: glance/image_cache/drivers/sqlite.py:496
#: glance/image_cache/drivers/xattr.py:446
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr "Cached image file '%s' doesn't exist, unable to delete"

#: glance/openstack/common/policy.py:262
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: glance/registry/api/v1/images.py:126
#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr "Invalid marker. Image %(id)s could not be found."

#: glance/registry/api/v1/images.py:131 glance/registry/api/v1/members.py:76
#: glance/registry/api/v1/members.py:111 glance/registry/api/v1/members.py:229
#: glance/registry/api/v1/members.py:293
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr "Access denied to image %(id)s but returning 'not found'"

#: glance/registry/api/v1/members.py:118 glance/registry/api/v1/members.py:236
#: glance/registry/api/v1/members.py:300
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr "User lacks permission to share image %(id)s"

#: glance/registry/api/v1/members.py:129 glance/registry/api/v1/members.py:146
#: glance/registry/api/v1/members.py:249
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr "Invalid membership association specified for image %(id)s"

#: glance/registry/api/v1/members.py:339
#, python-format
msgid "Member %(id)s not found"
msgstr "Member %(id)s not found"
