# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2015.1.dev182\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-18 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:403
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/scrubber.py:168
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/scrubber.py:191
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/scrubber.py:517
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr ""

#: glance/scrubber.py:618
#, python-format
msgid "%s file can not be created."
msgstr ""

#: glance/api/common.py:54
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:60
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:91
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/api/common.py:119
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/middleware/cache.py:169
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:268
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:287
msgid "Checksum header is missing."
msgstr ""

#: glance/api/v1/images.py:599
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:251
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v2/image_data.py:60
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:157
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:162
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:189
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr ""

#: glance/async/__init__.py:67
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:71
msgid "Internal error occurred while trying to process task."
msgstr ""

#: glance/common/store_utils.py:69
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment "
"of Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:47
#, python-format
msgid "Task not found for task_id %s"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:129
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:63
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:97
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr ""

#: glance/domain/__init__.py:474
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:269
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:398
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/xattr.py:109
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""

#: glance/openstack/common/lockutils.py:117
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: glance/openstack/common/policy.py:550 glance/openstack/common/policy.py:830
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: glance/openstack/common/policy.py:560
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: glance/registry/api/v1/images.py:136
msgid "Unable to get images"
msgstr ""

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Unable to show image %s"
msgstr ""

#: glance/registry/api/v1/images.py:390
#, python-format
msgid "Unable to delete image %s"
msgstr ""

#: glance/registry/api/v1/images.py:442
#, python-format
msgid "Unable to create image %s"
msgstr ""

#: glance/registry/api/v1/images.py:515
#, python-format
msgid "Unable to update image %s"
msgstr ""

#: glance/registry/client/v1/client.py:129
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr ""

